### ISSUE TITLE
[inventory] Location group not generated when "want_location" is specified

### ISSUE THREAD

**Issue by omenos** [theforeman/foreman-ansible-modules#1657]
##### SUMMARY

Generated inventory using `theforeman.foreman.foreman` plugin is not returning the `foreman_location_` attribute in `groups` and `group_names` despite `want_location` being specified in the configuration.

This was observed to be working with Foreman 3.5 which is the platform I initially built my workflows on. There is the hostvar `foreman_location_name` which can be used, but seeing how it exists whether or not `want_location` is defined it doesn't appear to be a replacement and the latter is truly missing.

Community post here: [Dynamic inventory reporting fewer groups than previous versions](https://community.theforeman.org/t/dynamic-inventory-reporting-fewer-groups-than-previous-versions/34613)

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

Experienced with both `ansible-core` 2.14 and 2.15.
```
ansible [core 2.14.8]
  config file = None
  configured module search path = ['/home/omenos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /scratch/foreman/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/omenos/.ansible/collections:/usr/share/ansible/collections
  executable location = /scratch/foreman/.venv/bin/ansible
  python version = 3.9.16 (main, Jan 17 2023, 18:53:15) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/scratch/foreman/.venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/omenos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /scratch/foreman/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/omenos/.ansible/collections:/usr/share/ansible/collections
  executable location = /scratch/foreman/.venv/bin/ansible
  python version = 3.9.16 (main, Jan 17 2023, 18:53:15) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/scratch/foreman/.venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection         Version
------------------ -------
theforeman.foreman 3.12.0
```

##### KATELLO/FOREMAN VERSION

```
foreman-3.6.1-1.el8.noarch
katello-4.8.2-1.el8.noarch
rubygem-katello-4.8.2-1.el8.noarch
```

##### STEPS TO REPRODUCE

Create a Foreman inventory requesting the location parameter.

```yaml
# foreman.yml
---
plugin: theforeman.foreman.foreman

# Foreman Server instance
url: "https://foreman.corp.tld"

# Foreman user and vault encrypted password
user: ""
password: ""

# Inventory collection parameters
use_reports_api: false
want_params: true
want_hostcollections: true
want_facts: true
want_location: true
```
Run tests to see if hosts have the requested groups are found.
```shell
$ ansible-inventory -i foreman.yml --graph

$ ansible $HOST -i foreman.yml -m debug -a "var=[groups,group_names]"
```

##### EXPECTED RESULTS

The resulting `groups` and `group_names` objects would contain `foreman_location_naus`.

##### ACTUAL RESULTS

```shell
$ ansible-inventory -i foreman.yml --graph -vvvv --vault-id @prompt
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/omenos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /scratch/foreman/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/omenos/.ansible/collections:/usr/share/ansible/collections
  executable location = /scratch/foreman/.venv/bin/ansible
  python version = 3.9.16 (main, Jan 17 2023, 18:53:15) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/scratch/foreman/.venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
Vault password (default): 
setting up inventory plugins
Loading collection ansible.builtin from 
host_list declined parsing /scratch/foreman/foreman.yml as it did not pass its verify_file() method
script declined parsing /scratch/foreman/foreman.yml as it did not pass its verify_file() method
Loading collection theforeman.foreman from /home/omenos/.ansible/collections/ansible_collections/theforeman/foreman
Using inventory plugin 'ansible_collections.theforeman.foreman.plugins.inventory.foreman' to process inventory source '/scratch/foreman/foreman.yml'
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fe366727af0> for vault_id=default
Parsed /scratch/foreman/foreman.yml inventory source with auto plugin
@all:
  |--@ungrouped:
  |  |--foreman.corp.tld
  |--@foreman_edge:
  |  |--@foreman_edge_groupa:
  |  |  |--group-a1.corp.tld
  |  |  |--group-a2.corp.tld
  |  |  |--group-a3.corp.tld
  |--@foreman_services:
  |  |--@foreman_services_groupb:
  |  |  |--@foreman_services_groupb_suba:
  |  |  |  |--gbsa1000.corp.tld
  |  |  |  |--gbsa1001.corp.tld
  |  |  |  |--gbsa1002.corp.tld
  |  |  |  |--gbsa1003.corp.tld
  |  |  |  |--gbsa1004.corp.tld
  |  |  |  |--gbsa1005.corp.tld
  |  |  |  |--gbsa1006.corp.tld
  |  |  |  |--gbsa1007.corp.tld
  |  |  |  |--gbsa1008.corp.tld
  |  |  |  |--gbsa1009.corp.tld


$ ansible gbsa1009.corp.tld -i foreman.yml -m debug -a "var=[groups,group_names]" -vvvv --vault-id @prompt
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/omenos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /scratch/foreman/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/omenos/.ansible/collections:/usr/share/ansible/collections
  executable location = /scratch/foreman/.venv/bin/ansible
  python version = 3.9.16 (main, Jan 17 2023, 18:53:15) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/scratch/foreman/.venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
Vault password (default):
setting up inventory plugins
Loading collection ansible.builtin from 
host_list declined parsing /scratch/foreman/foreman.yml as it did not pass its verify_file() method
script declined parsing /scratch/foreman/foreman.yml as it did not pass its verify_file() method
Loading collection theforeman.foreman from /home/omenos/.ansible/collections/ansible_collections/theforeman/foreman
Using inventory plugin 'ansible_collections.theforeman.foreman.plugins.inventory.foreman' to process inventory source '/scratch/foreman/foreman.yml'
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f636db3c970> for vault_id=default
Parsed /scratch/foreman/foreman.yml inventory source with auto plugin
Loading callback plugin minimal of type stdout, v2.0 from /scratch/foreman/.venv/lib64/python3.9/site-packages/ansible/plugins/callback/minimal.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
gbsa1009.corp.tld | SUCCESS => {
    "[groups,group_names]": [
        {
            "all": [ ... ],
            "foreman_edge": [ ... ],
            "foreman_edge_groupa": [ ... ],
            "foreman_services": [ ... ],
            "foreman_services_groupb": [ ... ],
            "foreman_services_groupb_suba": [ ... ],
            "ungrouped": [ ... ]
        },
        [
            "foreman_services",
            "foreman_services_groupb",
            "foreman_services_groupb_suba"
        ]
    ]
}
```

**Comment by evgeni** [comment]
`want_location` only works when you use the reports API (granted, this is not clearly documented), but you set `use_reports_api: false` so it's not considered.

That said, I would expect the `want_params: true` in this case to still report back a `foreman_location_name` host variable.

Your debug output only shows groups tho, and we (by default) do not assign a "location" group (you could via composed groups, if the variable is present, but that's not in your config right now).

**Comment by evgeni** [comment]
FTR, using your config against my test instance, I get:

```console
% ansible-inventory -i test.foreman.yml --list
{
    "_meta": {
        "hostvars": {
            "centos8-stream-katello-4-9.tanso.example.com": {
…
                "foreman_location_id": 2,
                "foreman_location_name": "Default Location",
            }
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "centos8-stream-katello-4-9.tanso.example.com"
        ]
    }
}
```

**Comment by evgeni** [comment]
And if I add:
```yaml
keyed_groups:
    - key: foreman_location_name
      prefix: ""
      separator: ""
```

I get:
```
{
    "Default_Location": {
        "hosts": [
            "centos8-stream-katello-4-9.tanso.example.com"
        ]
    },
    "_meta": {
        "hostvars": {
            "centos8-stream-katello-4-9.tanso.example.com": {
…
    },
    "all": {
        "children": [
            "ungrouped",
            "Default_Location"
        ]
    }
}
```

**Comment by omenos** [comment]
I should have clarified, the `use_reports_api` parameter is a relatively new addition to the config, I hadn't used it previously. As far as I can recall, I've always had the reports api warning so I figured adding that would shave some time off the inventory retrieval.

I could have sworn that I had seen the location listed as a group in AWX when I linked the two platforms, but now I'm no longer sure. And yes, I see the `foreman_location_name` hostvar attribute, I rekeyed my collection to use it instead the other day.

Composed groups is a new concept to me, I'll have to take a look at that.

**Comment by evgeni** [comment]
the docs for the groups magic is here: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/constructed_inventory.html

and yeah, if you got the warning, then you always were using the non-report code-path and should never got the group.

maybe you had one setup where reports were working, and one where not?

**Comment by omenos** [comment]
Following up on this, I think I figured out the reason why the Reports API is failing. It looks like disabling `want_content_facet_attributes` enables this to work as intended. While the parameter is set to `true`, the default, I see the following error in the "Render report Ansible - Ansible Inventory" task. This results in a `stopped:warning` task state rather than `stopped:success`.

<details>
<summary><strong>Task error logs</strong></summary>

```text
Action:
Dynflow::ActiveJob::QueueAdapters::JobWrapper

Input:
{"job_class"=>"TemplateRenderJob",
 "queue"=>"default",
 "job_data"=>
  {"job_class"=>"TemplateRenderJob",
   "job_id"=>"3d7e589e-1a3f-48de-83f0-a758b72322f6",
   "provider_job_id"=>"3d7e589e-1a3f-48de-83f0-a758b72322f6",
   "queue_name"=>"default",
   "priority"=>nil,
   "arguments"=>
    [{"template_id"=>144,
      "gzip"=>false,
      "send_mail"=>false,
      "mail_to"=>nil,
      "format"=>"json",
      "input_values"=>
       {"1"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "2"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "3"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "4"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "5"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "6"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "7"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "8"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "9"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "10"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "11"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "12"=>{"value"=>"yes", "_aj_hash_with_indifferent_access"=>true},
        "_aj_hash_with_indifferent_access"=>true},
      "_aj_hash_with_indifferent_access"=>true},
     {"user_id"=>5, "_aj_ruby2_keywords"=>["user_id"]}],
   "executions"=>0,
   "exception_executions"=>{},
   "locale"=>"en",
   "timezone"=>"UTC",
   "enqueued_at"=>"2023-08-16T00:22:53Z"},
 "current_request_id"=>"f290a685-602a-4b00-8a30-1241a89bf0c6",
 "current_timezone"=>"UTC",
 "current_organization_id"=>nil,
 "current_location_id"=>nil,
 "current_user_id"=>5}

Output:
{}

Exception:
Safemode::NoMethodError: undefined method '#single_content_view' for Katello::Host::ContentFacet::Jail (Katello::Host::ContentFacet)

Backtrace:
/usr/share/gems/gems/safemode-1.3.7/lib/safemode/jail.rb:22:in `method_missing'
Ansible - Ansible Inventory:88:in `block in bind'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches/batch_enumerator.rb:40:in `block (2 levels) in each_record'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches/batch_enumerator.rb:40:in `each'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches/batch_enumerator.rb:40:in `block in each_record'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches.rb:229:in `loop'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches/batch_enumerator.rb:39:in `each'
/usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/relation/batches/batch_enumerator.rb:39:in `each_record'
/usr/share/gems/gems/safemode-1.3.7/lib/safemode/jail.rb:31:in `method_missing'
Ansible - Ansible Inventory:82:in `bind'
/usr/share/gems/gems/safemode-1.3.7/lib/safemode.rb:51:in `eval'
/usr/share/gems/gems/safemode-1.3.7/lib/safemode.rb:51:in `eval'
/usr/share/foreman/app/services/foreman/renderer/safe_mode_renderer.rb:7:in `render'
/usr/share/foreman/app/services/foreman/renderer/base_renderer.rb:18:in `render'
/usr/share/foreman/app/services/foreman/renderer.rb:46:in `render'
/usr/share/foreman/app/models/template.rb:172:in `render'
/usr/share/foreman/app/models/report_composer.rb:241:in `render'
/usr/share/foreman/app/jobs/template_render_job.rb:12:in `block in perform'
/usr/share/foreman/app/models/concerns/foreman/thread_session.rb:108:in `as'
/usr/share/foreman/app/jobs/template_render_job.rb:9:in `perform'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/execution.rb:48:in `block in perform_now'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/share/gems/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:21:in `block in instrument'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:31:in `instrument'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/logging.rb:24:in `tag_logger'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/execution.rb:47:in `perform_now'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/execution.rb:25:in `block in execute'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:71:in `wrap'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/share/gems/gems/activejob-6.1.7.3/lib/active_job/execution.rb:23:in `execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/active_job/queue_adapter.rb:47:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:582:in `block (3 levels) in execute_run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action/progress.rb:31:in `with_progress_calculation'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action/progress.rb:17:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/load_setting_values.rb:20:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_request_id.rb:15:in `block in run'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_request_id.rb:52:in `restore_current_request_id'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_request_id.rb:15:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_timezone.rb:15:in `block in run'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_timezone.rb:44:in `restore_curent_timezone'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_timezone.rb:15:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `block in run'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_taxonomies.rb:45:in `restore_current_taxonomies'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:32:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:27:in `pass'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware.rb:19:in `pass'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_user.rb:15:in `block in run'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_user.rb:54:in `restore_curent_user'
/usr/share/gems/gems/foreman-tasks-7.2.1/app/lib/actions/middleware/keep_current_user.rb:15:in `run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/stack.rb:23:in `call'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/middleware/world.rb:31:in `execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:581:in `block (2 levels) in execute_run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:580:in `catch'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:580:in `block in execute_run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:483:in `block in with_error_handling'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:483:in `catch'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:483:in `with_error_handling'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:575:in `execute_run'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/action.rb:296:in `execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:18:in `block (2 levels) in execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/execution_plan/steps/abstract.rb:167:in `with_meta_calculation'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:17:in `block in execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:32:in `open_action'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:16:in `execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/director.rb:69:in `execute'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:11:in `block (2 levels) in perform'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/executors.rb:18:in `run_user_code'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:9:in `block in perform'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:25:in `with_telemetry'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:8:in `perform'
/usr/share/gems/gems/dynflow-1.6.8/lib/dynflow/executors/sidekiq/serialization.rb:27:in `perform'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:196:in `execute_job'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:163:in `block in process'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:112:in `local'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq.rb:39:in `block in <module:Sidekiq>'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:257:in `stats'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:13:in `call'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:79:in `global'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/logger.rb:11:in `with'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:33:in `prepare'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:123:in `dispatch'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:162:in `process'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:78:in `process_one'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:68:in `run'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:43:in `watchdog'
/usr/share/gems/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
/usr/share/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```
</details>

I've also updated the system to the next Katello patch version to see if this issue happened to be caught, but it was not.

```text
foreman-3.6.1-1.el8.noarch
katello-4.8.4-1.el8.noarch
rubygem-katello-4.8.3-1.el8.noarch
```

**Comment by evgeni** [comment]
> `Safemode::NoMethodError: undefined method '#single_content_view' for Katello::Host::ContentFacet::Jail (Katello::Host::ContentFacet)`

Hmm. Interesting. My test setup doesn't have content facets, so, this might behave differently. Lemme check.

**Comment by evgeni** [comment]
Yepp, that's a bug!

I've opened https://github.com/Katello/katello/pull/10699 to fix it :)

**Comment by omenos** [comment]
Awesome, thanks @evgeni!

**Comment by evgeni** [comment]
This has been merged in Katello (and I asked for cherry picks to the stable branches), and I also opened https://github.com/theforeman/foreman-ansible-modules/pull/1660 to better document that some options only work in Report API mode.

Is there anything else left in here, or should we close this issue?

**Comment by omenos** [comment]
> Is there anything else left in here, or should we close this issue?

I think this is good to be closed, since we the fix has been committed upstream and just waiting on stable branch backports. I'll apply the patch locally in our environment and see what happens.

Thanks again, Evgeni!
