### ISSUE TITLE
katello_upload ends with 405: Method not allowed

### ISSUE THREAD

**Issue by m-czernek** [theforeman/foreman-ansible-modules#602]
##### SUMMARY

When trying to execute katello_upload.py, I get the following error:

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_theforeman.foreman.katello_upload_payload_age_C8/ansible_theforeman.foreman.katello_upload_payload.zip/ansible_collections/theforeman/foreman/plugins/module_utils/foreman_helper.py", line 528, in fail_from_exception
    fail['error'] = exc.response.json()['error']

failed: [satellite.example.com -> localhost] (item=python2-junit_xml-1.7-1.el7.noarch.rpm) => {
    "ansible_loop_var": "content", 
    "changed": false, 
    "content": {
        "filename": null, 
        "organization": "org_RH", 
        "product": "prod_custom", 
        "repository": "zzz_test", 
        "src": "python2-junit_xml-1.7-1.el7.noarch.rpm"
    }, 
    "error": "{\"displayMessage\":\"405 Method Not Allowed\",\"errors\":[\"405 Method Not Allowed\"]}", 
    "invocation": {
        "module_args": {
            "organization": "org_RH", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "product": "prod_custom", 
            "repository": "zzz_test", 
            "server_url": "https://satellite.example.com", 
            "src": "/usr/local/share/packages/python2-junit_xml-1.7-1.el7.noarch.rpm", 
            "username": "admin", 
            "validate_certs": true
        }
    }, 
    "msg": "Error while performing update on content_uploads: 400 Client Error: Bad Request"
}
```

Also:

```
ll "/usr/local/share/packages/python2-junit_xml-1.7-1.el7.noarch.rpm"
-rwxrwxrwx. 1 root root 13800 Nov 14 12:10 /usr/local/share/packages/python2-junit_xml-1.7-1.el7.noarch.rpm
```

Product and repositories exist in my Satellite.

This is the latest version of katello_upload.py (from master, couple minutes ago)

##### ISSUE TYPE
 - Bug Report

**Comment by evgeni** [comment]
which Katello/Satellite version is that?

**Comment by m-czernek** [comment]
Sat version: `Version 6.5.2.1`

**Comment by evgeni** [comment]
Weird. Can you have a look at `/var/log/foreman/production.log` and share the part where the upload happens. Feel free to mail me that (evgeni@redhat), so that you don't spill any private data.

**Comment by evgeni** [comment]
a few observations after debugging this together with @m-czernek:
* the RPM in question is https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python2-junit_xml-1.7-1.el7.noarch.rpm
* the upload of the same RPM works just fine via UI and hammer
* the error we see is returned from Pulp, and Katello just passes it on
* the exception looks like this in `production.log`:
```
2019-11-22T09:05:22 [E|kat|83024895] PUT: https://satellite.example.com/pulp/api/v2/content/uploads/5efe9a48-9913-41fb-92ff-cd76bfe73182///: {"content_type"=>"application/json", "accept"=>"application/json"}
405 Method Not Allowed:
2019-11-22T09:05:22 [E|app|83024895] exception when talking to a remote client: 405 Method Not Allowed RestClient::MethodNotAllowed: 405 Method Not Allowed
Body:
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:103:in `return!'
/opt/theforeman/tfm/root/usr/share/gems/gems/runcible-2.11.1/lib/runcible/base.rb:95:in `block in get_response'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:807:in `process_result'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:725:in `block in transmit'
/opt/rh/rh-ruby25/root/usr/share/ruby/net/http.rb:910:in `start'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:715:in `transmit'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:145:in `execute'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `execute'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/resource.rb:76:in `put'
/opt/theforeman/tfm/root/usr/share/gems/gems/runcible-2.11.1/lib/runcible/base.rb:94:in `get_response'
/opt/theforeman/tfm/root/usr/share/gems/gems/runcible-2.11.1/lib/runcible/base.rb:74:in `call'
/opt/theforeman/tfm/root/usr/share/gems/gems/runcible-2.11.1/lib/runcible/resources/content.rb:30:in `upload_bits'
/opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.10.0.55/app/controllers/katello/api/v2/content_uploads_controller.rb:21:in `update'
```
* what makes me wonder is the `///` at the end of the URL Katello constructs here, my guess would be that this makes some route in Django not match and Pulp explodes

**Comment by evgeni** [comment]
I can't reproduce this with tfm-rubygem-katello-3.13.1, will try a 3.10 on monday.

**Comment by evgeni** [comment]
nope, also fine on 3.10 :/

**Comment by evgeni** [comment]
so I was finally able to repro this, by using FAM on a RHEL7 box. let's see what's different.

**Comment by m-czernek** [comment]
CC @gabriel-mh if the upstream needs more debugging info

**Comment by evgeni** [comment]
Getting closer.

This is a valid request:

```
2019-11-25T09:51:04 [I|app|] Started PUT "/katello/api/repositories/3/content_uploads/5478e824-f1e1-44c1-b87c-b5d21dd0d08e" for 192.168.121.1 at 2019-11-25 09:51:04 +0000
2019-11-25T09:51:04 [I|app|72fae1b2] Processing by Katello::Api::V2::ContentUploadsController#update as JSON
2019-11-25T09:51:04 [I|app|72fae1b2]   Parameters: {"content"=>"[FILTERED]", "offset"=>"0", "api_version"=>"v2", "repository_id"=>"3", "id"=>"5478e824-f1e1-44c1-b87c-b5d21dd0d08e"}
```

and this one is failing
```
2019-11-25T10:00:33 [I|app|] Started PUT "/katello/api/repositories/5/content_uploads/2c713548-8fc8-4c43-b68b-4d682fc17fab" for ::1 at 2019-11-25 10:00:33 +0000
2019-11-25T10:00:33 [I|app|399b1303] Processing by Katello::Api::V2::ContentUploadsController#update as JSON
2019-11-25T10:00:33 [I|app|399b1303]   Parameters: {"api_version"=>"v2", "repository_id"=>"5", "id"=>"2c713548-8fc8-4c43-b68b-4d682fc17fab", "content_upload"=>{}}
```

for some reason the `offset` is missing and there is `content_upload` empty o_O

**Comment by evgeni** [comment]
and by downgrading `requests` to 2.6.0 (that's the version in RHEL), I can reproduce this on my Fedora too. great.

**Comment by evgeni** [comment]
@m-czernek @gabriel-mh I will release a new apypie version soon, but the patch should apply cleanly in your env too.

**Comment by evgeni** [comment]
(pushed 0.2.1 to pypi, and my copr is building an RPM too)
