### ISSUE TITLE
foreman.foreman_user fails to create new user

### ISSUE THREAD

**Issue by flyemsafe** [theforeman/foreman-ansible-modules#662]
##### SUMMARY
The foreman.foreman_user fails when creating a new user.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.12.0.29-1.el7sat.noarch
foreman-1.22.0.33-1.el7sat.noarch

```

##### APYPIE VERSION

```
Metadata-Version: 1.1
Version: 0.2.1

```

##### STEPS TO REPRODUCE

```yaml
- name: create user for role
  theforeman.foreman.foreman_user:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: bob
    firstname: Tom
    lastname: Cat
    description: Pilot
    user_password: blueangels
    default_location: Portlanda
    default_organization: ACME
    state: present
    auth_source: Internal
    organizations:
      - ACME
    locations:
      - Portlanda
  tags: [katello,user]

```

##### EXPECTED RESULTS

User created.

##### ACTUAL RESULTS

 Playbook fails

```
Thursday 12 December 2019  20:59:58 -0500 (0:00:01.318)       0:00:05.131 ***** 
fatal: [qbn-sat01]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to 172.24.24.113 closed.
  module_stdout: |-
    /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    Traceback (most recent call last):
      File "/home/admin/.ansible/tmp/ansible-tmp-1576202398.09-88656991678435/AnsiballZ_foreman_user.py", line 114, in <module>
        _ansiballz_main()
      File "/home/admin/.ansible/tmp/ansible-tmp-1576202398.09-88656991678435/AnsiballZ_foreman_user.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/admin/.ansible/tmp/ansible-tmp-1576202398.09-88656991678435/AnsiballZ_foreman_user.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/tmp/ansible_theforeman.foreman.foreman_user_payload_9Kz4QL/__main__.py", line 574, in <module>
      File "/tmp/ansible_theforeman.foreman.foreman_user_payload_9Kz4QL/__main__.py", line 548, in main
    TypeError: 'NoneType' object has no attribute '__getitem__'
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```

**Comment by evgeni** [comment]
You're missing the `mail` attribute which is documented as being required for new users (but we don't check that, will fix).
